import {Routes} from '../routes';

export const accessoriesName = [
  {title: 'PEHD', route: Routes.PreHeater, disable: false},
  {title: 'PHWD', route: Routes.PreHeater, disable: false},
  {title: 'HWD', route: Routes.PostHeater, disable: false},
  {title: 'EHD', route: Routes.PostHeater, disable: false},
  {title: 'CWD', route: Routes.PostCooling, disable: false},
  {title: 'AWP', route: Routes.Bypass, disable: false},
  {title: 'DXD', route: null, disable: true},
  {title: 'DPVV2', route: Routes.Bypass, disable: false},
  {title: 'PCAP', route: null, disable: true},
  {title: 'PCAF', route: null, disable: true},
  {title: 'DPS', route: null, disable: true},
  {title: 'IN', route: null, disable: true},
  {title: 'OUT', route: null, disable: true},
  {title: 'EBPD2', route: Routes.Bypass, disable: false},
  {title: 'P1VOC', route: Routes.Bypass, disable: false},
  {title: 'SSR', route: Routes.PostHeater, disable: false},
  {title: 'P1RH', route: Routes.Bypass, disable: false},
  {title: 'P2RH', route: Routes.Bypass, disable: false},
  {title: 'EBPD', route: Routes.Bypass, disable: false},
  {title: 'P1CO2', route: Routes.Bypass, disable: false},
  {title: 'P2CO2', route: Routes.Bypass, disable: false},
  {title: 'EXT1', route: Routes.Bypass, disable: false},
  {title: 'EXT2', route: Routes.Bypass, disable: false},
  {title: 'EXT3', route: Routes.Bypass, disable: false},
  {title: 'EXT4', route: Routes.Bypass, disable: false},
  {title: 'FLW1', route: null, disable: true},
  {title: 'FLW2', route: null, disable: true},
  {title: 'DSC', route: null, disable: true},
  {title: 'GLOBAL', route: null, disable: true},
  {title: 'BPD', route: Routes.Bypass, disable: false},
  {title: 'FKI', route: null, disable: true},
  {title: 'MBUS', route: null, disable: true},
];
